http://localhost:8080/dad-jokes


###

http://localhost:8080/jokes?message=universe



###

http://localhost:8080/youtube


###

http://localhost:8080/music


###

http://localhost:8080/books

###

http://localhost:8080/olympics/2024?stuffit=true